name: Hydro-LSTM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom
  - appdirs
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - contourpy
  - cryptography
  - cycler
  - expat
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - gettext
  - gmp
  - gnutls
  - geopandas
  - icu
  - idna
  - joblib
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libidn2
  - liblapack
  - libopenblas
  - libopus
  - libpng
  - libprotobuf
  - libsqlite
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - matplotlib
  - matplotlib-base
  - mkl
  - munkres
  - ncurses
  - nettle
  - numpy
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pandas
  - pillow
  - pip
  - pooch
  - pthread-stubs
  - pycparser
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sleef
  - svt-av1
  - tbb
  - threadpoolctl
  - tk
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - typing_extensions
  - unicodedata2
  - urllib3
  - wheel
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zstd
